### ISSUE TITLE
Lol. I did the final level :D

### ISSUE THREAD

**Issue by mrfambo** [Paol-imi/the-aviator#1]
I saw your post about react-repainting and came to your github. While checking repositories i saw this repository. 
I STARTED PLAYING IT AND COULDN'T LEAVE IT UNFINISHED :D

![riddledone](https://user-images.githubusercontent.com/16781300/82741879-77cc5800-9d70-11ea-9347-fa53ee0d52a9.png)

**Comment by mrfambo** [comment]
IT TOOK ME AN HOUR :D

**Comment by paol-imi** [comment]
I'm glad you liked it, but the one in the image is a demo of another project. The real game is this

https://paol-imi.github.io/the-aviator/

<img src="https://github.com/Paol-imi/the-aviator/blob/master/images/screens/game.gif?raw=true" />

The last level should take you more than one hour :)
